import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAtomValue } from 'jotai'
import { Radio } from 'lucide-react'
import { searchResultsAtom } from '@/store/aiSearchAtom'
import { authAtom } from '@/store/authAtom'
import { useSaveContent } from '@/hooks/useSaveContent'
import { useVerifyContent } from '@/hooks/useVerifyContent'
import PatientTopNav from '@/components/PatientTopNav'
import SourceCard from './components/SourceCard'
import type { SavedContent } from '@/types'
import { cn } from '@/lib/utils'
import './AiSearchResultsPage.css'

type FilterKey = 'all' | 'physio' | 'trainer' | 'both'

const FILTERS: { key: FilterKey; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'physio', label: 'Verified by Physio' },
  { key: 'trainer', label: 'Verified by Trainer' },
  { key: 'both', label: 'Verified by Physio & Trainer' },
]

function verificationRank(source: SavedContent): number {
  const hasPhysio = source.verifiedBy.includes('THERAPIST')
  const hasCoach = source.verifiedBy.includes('TRAINER')
  if (hasPhysio && hasCoach) return 3
  if (hasPhysio) return 2
  if (hasCoach) return 1
  return 0
}

function applyFilter(sources: SavedContent[], filter: FilterKey): SavedContent[] {
  switch (filter) {
    case 'physio':
      return sources.filter((s) => s.verifiedBy.includes('THERAPIST'))
    case 'trainer':
      return sources.filter((s) => s.verifiedBy.includes('TRAINER'))
    case 'both':
      return sources.filter(
        (s) => s.verifiedBy.includes('THERAPIST') && s.verifiedBy.includes('TRAINER'),
      )
    default:
      return sources
  }
}

export default function AiSearchResultsPage() {
  const navigate = useNavigate()
  const results = useAtomValue(searchResultsAtom)
  const auth = useAtomValue(authAtom)
  const [activeFilter, setActiveFilter] = useState<FilterKey>('all')
  const [savedIds, setSavedIds] = useState<Set<string>>(new Set())

  const saveContent = useSaveContent((item) => {
    setSavedIds((prev) => new Set([...prev, item.recommendation_id]))
  })
  const verifyContent = useVerifyContent()

  if (!results) {
    return (
      <div className="ais-results ais-results--empty">
        <p>No results found. Please go back and search again.</p>
        <button className="ais-results__back-link" onClick={() => navigate('/ai-search')}>
          Back to Search
        </button>
      </div>
    )
  }

  const { query, sources } = results
  const userRole = auth?.role ?? 'PATIENT'

  const sortedSources = [...sources].sort((a, b) => verificationRank(b) - verificationRank(a))
  const filteredSources = applyFilter(sortedSources, activeFilter)

  return (
    <div className="ais-results pt-16">
      <PatientTopNav patientName={auth?.first_name} />

      <main className="ais-results__main">
        {/* Original query */}
        <p className="ais-results__query">
          &ldquo;{query.query_content}&rdquo;
        </p>

        {/* AI Summary card */}
        <div className="ais-results__ai-card">
          <div className="ais-results__ai-header">
            <Radio size={18} className="ais-results__ai-wave" />
            <span className="ais-results__ai-label">AI Summary</span>
          </div>
          <div className="ais-results__ai-disclaimer">
            <span className="ais-results__gemini-badge">G</span>
            <span>Generated by Gemini AI · Always consult your healthcare professional</span>
          </div>
          <p className="ais-results__ai-body">{query.ai_response}</p>
        </div>

        {/* Filter chips */}
        <div className="ais-results__filters" role="group" aria-label="Filter results">
          {FILTERS.map(({ key, label }) => (
            <button
              key={key}
              className={cn(
                'ais-results__chip',
                activeFilter === key && 'ais-results__chip--active',
              )}
              onClick={() => setActiveFilter(key)}
            >
              {label}
            </button>
          ))}
        </div>

        {/* Source cards */}
        <section className="ais-results__sources">
          <h2 className="ais-results__sources-title">Medical Sources</h2>
          <div className="ais-results__source-list">
            {filteredSources.map((source) => (
              <SourceCard
                key={source.recommendation_id}
                source={source}
                userRole={userRole}
                onSave={(item) => saveContent.mutate(item)}
                onVerify={(id, role) => verifyContent.mutate({ recommendationId: id, role })}
                savedIds={savedIds}
              />
            ))}
            {filteredSources.length === 0 && (
              <p className="ais-results__no-results">No sources match this filter.</p>
            )}
          </div>
        </section>
      </main>
    </div>
  )
}
